/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Cloud_AmrDecoder */

#ifndef _Included_Cloud_AmrDecoder
#define _Included_Cloud_AmrDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Cloud_AmrDecoder
 * Method:    AmrDecoderInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Cloud_AmrDecoder_AmrDecoderInit
  (JNIEnv *, jobject);

/*
 * Class:     Cloud_AmrDecoder
 * Method:    AmrDecoderProcess
 * Signature: (II[SI[S)I
 */
JNIEXPORT jint JNICALL Java_Cloud_AmrDecoder_AmrDecoderProcess
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jshortArray);




/*
 * Class:     Cloud_AmrDecoder
 * Method:    AmrDecoderExit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Cloud_AmrDecoder_AmrDecoderExit
  (JNIEnv *, jobject, jint st);

#ifdef __cplusplus
}
#endif
#endif
